### ISSUE TITLE
"No Codec Info"

### ISSUE THREAD

**Issue by jixiangpingping** [deepch/RTSPtoWSMP4f#1]
when I config the RTSP url  and run ,it always says "No Codec Info". why?

**Comment by deepch** [comment]
Check that there is SDP. Make sure the camera codec is h264 and not h265

**Comment by jixiangpingping** [comment]
demo4 dial tcp rtsp ip: connect: operation timed out

**Comment by deepch** [comment]
you can try rtsp://171.25.232.5/3e3019c02ad14b84bceb2b810db29918

**Comment by deepch** [comment]
I found you audio raw pcm? update depend and try now
