### ISSUE TITLE
How to handle frame get stucked

### ISSUE THREAD

**Issue by yeshivsher** [deepch/RTSPtoWSMP4f#11]
It works great when the RTSP is locally, but when I playing it from remote via static IP the streaming get stack sometimes and I want to catch the error in order to know why and let the client (in my case using the web via Iframe) refresh or just no that something wrong in the streaming.

Not familiar with GO, please help.

BTW, hoping the new service RTSPtoWeb will solve it...

**Comment by vdalex25** [comment]
where does the error occur on the server or in the browser? and how is it expressed?

**Comment by yeshivsher** [comment]
It doesn't, that's the problem.
The streaming get stacked and nothing shows

**Comment by vdalex25** [comment]
Server get stream from camera and send stream data to browser  over websocket

**Comment by yeshivsher** [comment]
Wow thx man
but I think it's a camera issue, no errors in the console.
The ws connection looks like it's still connected but the cameras streaming is very slow.
Is there any way to catch this kind of error?
Also it takes couple seconds to actually show the camera since it connects - can I catch it too?

**Comment by vdalex25** [comment]
to start playing the video, the browser needs to buffer several frames, and this time depends on the camera settings such as frame rate, etc.  - for example the lower the fps, the longer the delay before starting
it's time between loadstart event and canplaythrough event 
can you give me rtsp link to your camera to check?

**Comment by yeshivsher** [comment]
Wish I could... it's a security camera.
Can you tell me what to do?
How to get fps and configure it in this service?

**Comment by yeshivsher** [comment]
> to start playing the video, the browser needs to buffer several frames, and this time depends on the camera settings such as frame rate, etc.  - for example the lower the fps, the longer the delay before starting
> 
> it's time between loadstart event and canplaythrough event 
> 
> can you give me rtsp link to your camera to check?

Can u tell how to configure FPS here?

**Comment by deepch** [comment]
fps - configure on IP camera or other rtsp streamer

this programs no change video not decode or encode h264 

open ip page and configure your rtsp ftp

![ip-camera-video-encode-settings](https://user-images.githubusercontent.com/7899955/103899895-235fc800-5108-11eb-89c6-c3325f14b76e.png)

**Comment by yeshivsher** [comment]
That for the camera, how about this program?
What is the default fps?
Is it configurable?

And thanks!

**Comment by deepch** [comment]
no fps is not configured in the program.
