### ISSUE TITLE
Memory is constantly increasing, there is no trace of release

### ISSUE THREAD

**Issue by xiongfeigood** [deepch/RTSPtoWSMP4f#12]
Hello, I can play the video normally when I open it with the browser, but as time goes by, I find that the memory occupied by the browser keeps increasing without any trace of release. Less than an hour, the memory is more than 2G, can you help to solve this problem? thank you

**Comment by vdalex25** [comment]
Hi, can you tell me which browser and operating system you are using?
the browser has a limited buffer size and clears the buffer itself before overflow
[here is the buffer size for different browsers](https://developers.google.com/web/updates/2017/10/quotaexceedederror#how_much_data_can_i_append)
I tested yesterday - at the start, the tab occupied 63 MB of memory, after an hour - 304 MB, after two hours - 307 MB
![start](https://user-images.githubusercontent.com/33447958/104813312-7a0c8680-5819-11eb-85b0-c49d5631a64d.png)
![1 hours play](https://user-images.githubusercontent.com/33447958/104813167-7b897f00-5818-11eb-96e7-a8bfbec09cee.png)
![2 hours play](https://user-images.githubusercontent.com/33447958/104813169-80e6c980-5818-11eb-85fc-d14a6f3a8c73.png)

**Comment by xiongfeigood** [comment]
Hi,I use Firefox browser, Win10. I look in the task manager and there are 6 threads. Is the code I use different from yours?

**Comment by vdalex25** [comment]
i use latest version of code
tested on FireFox  84.0.2 win 10 
at start in firefox task manager (about:performance) tab occupied 39,7 MB of memory  
windows task manager firefox occupied 407,2 MB of memory  
 after an hour firefox task manager - 110,3 MB, windows task manager 436,3 MB
start
![start](https://user-images.githubusercontent.com/33447958/104852725-a1dd1680-590d-11eb-8092-55d059557ff4.PNG)
1hour play 
![1hour](https://user-images.githubusercontent.com/33447958/104852727-a4d80700-590d-11eb-8568-3243202198e3.PNG)

**Comment by vdalex25** [comment]
Memory is constantly increasing if browser console is open and params verbose in file app.js is true

**Comment by xiongfeigood** [comment]
Hello, I have tested the problem exactly as you said. Thank you very much for your help. This problem has been solved successfully. I also have a question to ask for help: how to save the fetching RTSP stream as a image on the server side? thank you

**Comment by deepch** [comment]
I'll give you an example of this operation, but it will depend on ffmpeg to make a picture of the frame.

**Comment by xiongfeigood** [comment]
Hello, I have achieved the snapshot by FFMPEG method, thank you. Actually, I wanted to ask how to get RTSP images natively through Golang.

**Comment by deepch** [comment]
There is no native library for decoding h264 a video frame into a picture on golang.  

1) make binary and use exec
2) make image server and use socket to send raw frame to server
3) make image server use cuda and use socket to send raw frame to server
4) grab image from camera over socket http://IP/snapshot 

and etc....

**Comment by xiongfeigood** [comment]
Thank you very much for your thoughts. Thank you
