### ISSUE TITLE
Sir Can support H264_PCMALAW

### ISSUE THREAD

**Issue by PittYao** [deepch/RTSPtoWSMP4f#13]
that's all 。thank you for your reply 。
![image](https://user-images.githubusercontent.com/26101917/105968225-c5e4e880-60c1-11eb-9f91-b16e123898b9.png)
![image](https://user-images.githubusercontent.com/26101917/105968346-f0cf3c80-60c1-11eb-8534-b8a4fb37aa88.png)

**Comment by vdalex25** [comment]
Hi, can you give me a link to your stream for test ?

**Comment by PittYao** [comment]
> Hi, can you give me a link to your stream for test ?
Sorry,My camera is an intranet, I will try to make it into the Internet and test it for you

**Comment by vdalex25** [comment]
browser does not support pcm codec in mp4 container, pcm support only in wav container.

**Comment by deepch** [comment]
just writing an AAC encoder writer is a big task. sorry.

**Comment by PittYao** [comment]
> just writing an AAC encoder writer is a big task. sorry.

thank u bro.Thank you for this project.I am using your other project RTSP2WebRTC. that's great. I will continue to pay attention to you . should i close this issues?

**Comment by deepch** [comment]
nice to meet you see you later bro, look  a https://github.com/deepch/RTSPtoWeb new project
