### ISSUE TITLE
Не открывает изображение

### ISSUE THREAD

**Issue by vash-sa** [deepch/RTSPtoWSMP4f#15]
Добрый день! Решил последовать вашему совету и попробовать RTSPtoWSMP4f для передачи видео с камеры RTSP в браузер. Столкнулся с тем, что изображение не воспроизводится ни с моей камеры, ни с ваших примеров. При том, что  RTSPtoWebRTC изображение с моей камеры прекрасно воспроизводит. Сразу оговорюсь, что звук меня не интересует. Пока пытаюсь сделать все в локальной сети. Помогите, пожалуйста, разобраться в чем дело?

Вывод в консоли:

``[GIN-debug] GET    /                         --> main.serveHTTP.func1 (3 handlers)
[GIN-debug] GET    /player/:suuid            --> main.serveHTTP.func2 (3 handlers)
[GIN-debug] GET    /ws/:suuid                --> main.serveHTTP.func3 (3 handlers)
[GIN-debug] GET    /static/*filepath         --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (3 handlers)
[GIN-debug] HEAD   /static/*filepath         --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (3 handlers)
[GIN-debug] Listening and serving HTTP on :8083
[GIN] 2021/02/16 - 08:24:40 | 200 |    9.422189ms |   192.168.1.154 | GET      "/player/H265"
[GIN] 2021/02/16 - 08:24:40 | 200 |   49.387034ms |   192.168.1.154 | GET      "/static/js/app.js?ver=2021-02-16%2008%3a24%3a40.54063974%20%2b0000%20UTC%20m%3d%2b11.089518110"
[GIN] 2021/02/16 - 08:24:59 | 200 |     5.75281ms |   192.168.1.154 | GET      "/player/MICRO"
[GIN] 2021/02/16 - 08:24:59 | 200 |     790.057µs |   192.168.1.154 | GET      "/static/js/app.js?ver=2021-02-16%2008%3a24%3a59.914388279%20%2b0000%20UTC%20m%3d%2b30.463266482"
[GIN] 2021/02/16 - 08:25:22 | 200 |    6.084966ms |   192.168.1.154 | GET      "/player/H264_PCMALAW"
[GIN] 2021/02/16 - 08:25:22 | 200 |     865.179µs |   192.168.1.154 | GET      "/static/js/app.js?ver=2021-02-16%2008%3a25%3a22.695737523%20%2b0000%20UTC%20m%3d%2b53.244615726"
[GIN] 2021/02/16 - 08:25:33 | 200 |    5.774351ms |   192.168.1.154 | GET      "/player/H264_PCMALAW"
[GIN] 2021/02/16 - 08:25:33 | 200 |     785.724µs |   192.168.1.154 | GET      "/static/js/app.js?ver=2021-02-16%2008%3a25%3a33.037778801%20%2b0000%20UTC%20m%3d%2b63.586657046"
[GIN] 2021/02/16 - 08:26:03 | 200 |    5.148621ms |   192.168.1.154 | GET      "/player/H264_MY-CAM"
[GIN] 2021/02/16 - 08:26:03 | 200 |     866.971µs |   192.168.1.154 | GET      "/static/js/app.js?ver=2021-02-16%2008%3a26%3a03.302493357%20%2b0000%20UTC%20m%3d%2b93.851371768"
[GIN] 2021/02/16 - 08:26:27 | 200 |     5.72881ms |   192.168.1.154 | GET      "/player/H264_MY-CAM"
[GIN] 2021/02/16 - 08:26:27 | 200 |     735.434µs |   192.168.1.154 | GET      "/static/js/app.js?ver=2021-02-16%2008%3a26%3a27.217189096%20%2b0000%20UTC%20m%3d%2b117.766067300"

Индикатор загрузки крутится вечно, видео не появляется

**Comment by vash-sa** [comment]
Камера IP HiWatch. Браузер Google Chrome. Использую Golang 1.15.

**Comment by vash-sa** [comment]
Нашел. Почему. В app.js строго указан адрес потока 127.0.0.1, а я пытался воспроизвести из локальной сети. Можно вопрос закрывать. Видео появилось. Спасибо вам за помощь.

**Comment by deepch** [comment]
Ну и отлично!
