### ISSUE TITLE
Добавление потоков на лету

### ISSUE THREAD

**Issue by EugeneTV** [deepch/RTSPtoWSMP4f#17]
Добрый день! Очень хотелось бы иметь возможность добавлять потоки в течение работы сервиса. Или, как вариант, перечитывать конфиг, без остановки сервиса

**Comment by deepch** [comment]
Есть в https://github.com/deepch/RTSPtoWeb по сути то же самое но с более развёрнутым функционалом.

**Comment by EugeneTV** [comment]
Да, спасибо, обнаружил этот проект, то что нужно.
