### ISSUE TITLE
RTSP/1.0 461 client error

### ISSUE THREAD

**Issue by chygfm** [deepch/RTSPtoWSMP4f#19]
I use vlc to provide a rtsp  ,but it's err
![image](https://user-images.githubusercontent.com/62176381/111095599-c1449880-8578-11eb-8bf4-6deecaba899a.png)

![image](https://user-images.githubusercontent.com/62176381/111095599-c1449880-8578-11eb-8bf4-6deecaba899a.png)

RTSP/1.0 461 Client error.

How to solve it,please?

**Comment by deepch** [comment]
To understand what the errors are, I need access to your stream. Can you give me access to it over the Internet?
