### ISSUE TITLE
Not working using Chrome in iPhone 

### ISSUE THREAD

**Issue by yeshivsher** [deepch/RTSPtoWSMP4f#21]
cannon display the video in iPhone

**Comment by yeshivsher** [comment]
anyone?

**Comment by deepch** [comment]
IOS not supported MSE streaming

**Comment by yeshivsher** [comment]
OK
do you have a service that can support this?
can I solve it in this project?

**Comment by deepch** [comment]
hls, hlsLL, mjpeg, webrtc

**Comment by yeshivsher** [comment]
thx!

**Comment by yeshivsher** [comment]
> hls, hlsLL, mjpeg, webrtc

I have tried hls and it did not work on iphone

**Comment by deepch** [comment]
Ask a question in the hls repository
