### ISSUE TITLE
Delay compare to VLC

### ISSUE THREAD

**Issue by yeshivsher** [deepch/RTSPtoWSMP4f#23]
Very good job!

but I compared the rtsp streaming to vlc rtsp and after a minute or two the go service have delay that growing all the time

**Comment by deepch** [comment]
This is very strange, I ran the test for a day. Can you give access to your stream?

**Comment by yeshivsher** [comment]
this one for example: rtsp://stream.strba.sk:1935/strba/VYHLAD_JAZERO.stream
I did this test on local camera too.

![image](https://user-images.githubusercontent.com/46486647/121014627-dbba9680-c7a2-11eb-976a-437160bd875d.png)

**Comment by deepch** [comment]
Will I deal with this a little later, if not urgently?

**Comment by yeshivsher** [comment]
Actually, it is urgent for me...
I will really appreciate it if you can just tell me how to solve it I appreciate it!
of course, you don't have to...
it is a security system that really on this service.

**Comment by yeshivsher** [comment]
And thank you for the reply!

**Comment by yeshivsher** [comment]
I think I see the problem.
once I minimize the browser window the streaming stoped.

**Comment by yeshivsher** [comment]
Let me know when you have time for that.
thank you very much!

**Comment by yeshivsher** [comment]
> This is very strange, I ran the test for a day. Can you give access to your stream?

hi
did you check this?

**Comment by deepch** [comment]
The latency in hls is ok; it needs a segment cache to work. I checked mp4f, but I didn't see any delay like yours.
