### ISSUE TITLE
RTSPtoWSMP4f stream can lag several hours behind source

### ISSUE THREAD

**Issue by ddevz** [deepch/RTSPtoWSMP4f#3]
When viewing a video stream via RTSPtoWSMP4f, things go well for a while, but when you switch tabs, the browser (chrome in particular) will try to slow all background tabs down (to try to prevent them from dragging down the system).  I believe this causes the subroutines displaying the live video to slow down.

I am not familiar with the details of what you have written (by the way, thanks!), but i'm assuming it's the player part that's lagging.  If so, is there a way that when it's behind, the player could drop all the frames up to the most recently received keyframe and start playing at that keyframe?

TO REPLICATE:
 * open chrome
 * open a live video stream to a camera in tab 1
   - confirm that you are seeing live video
 * open a live video stream to a different camera in tab 2
   - confirm that you are seeing live video
 * open a live video stream to yet another camera in tab 3
 * go home leaving tab 3 as the displaying tab
 * come back the next day.  tab 3 may be in sync, but when you go to tab 1 or tab 2, they show you video of what happened several hours ago.

**Comment by vdalex25** [comment]
Browser pauses video without sound in background tab
change current time to end when tab is hidden
add to the **function loadPacket()**  next code
```
  if (livestream.buffered.length > 0) {
    if (typeof document.hidden !== "undefined" && document.hidden) {
      if (typeof livestream.webkitAudioDecodedByteCount!== "undefined"  && livestream.webkitAudioDecodedByteCount > 0) {
        //stream has sound but in background it may lag behind
        if ((livestream.buffered.end((livestream.buffered.length - 1)) - livestream.currentTime) > 10) {
          //more 10 seconds lag
          livestream.currentTime = livestream.buffered.end((livestream.buffered.length - 1)) - 0.5;
        }
      } else {
        //no sound, browser paused video without sound in background
        livestream.currentTime = livestream.buffered.end((livestream.buffered.length - 1)) - 0.5;
      }
    }
  }
```

**Comment by ddevz** [comment]
Wow!  Not only did it fix the stated problem, but it also resolves other lag issues that would occur even when the tab hasn't been backgrounded!  This is great.  Once I get to test it more thoroughly  I'll coming back and close this out.

Can this get added to the master branch?

**Comment by ddevz** [comment]
Further testing seems to show it working very well.  Thanks. 

Closing
