### ISSUE TITLE
High Latency

### ISSUE THREAD

**Issue by petryx** [deepch/RTSPtoWSMP4f#31]
Hi @deepch,

Firstable your project is very good. Congratulations for your work.

I'm trying to fix a high latency, about 5 seconds. There is a way to fine tune the initialization of a view, I think this delay is caused in the initialization of the video.

Could you indicate if possible where to make an adjustment to the source code? 

![delay_5s_LI](https://user-images.githubusercontent.com/101747/133122085-711a0e0a-5405-41ca-864a-3f3bc4620f73.jpg)

**Comment by deepch** [comment]
Do you have such a delay in all browsers?

**Comment by petryx** [comment]
Yes, I tested it on Chrome and Firefox, and both there is the same behavior

**Comment by vdalex25** [comment]
please tell me how do you measure the delay?
it is a bad idea compare the time set on the camera with the time in the operating system

**Comment by petryx** [comment]
Hello @vdalex25, you are right.

I took another measurement using the camera's own software.

And in this measurement, a very high delay appears. As seen in the image below.

![Browser_vs_cam](https://user-images.githubusercontent.com/101747/133131840-d5f247d4-dfc5-4e10-85c5-e8ced6ee5382.png)


But when I refresh the page the delay disappears.

![Browser_vs_cam_2](https://user-images.githubusercontent.com/101747/133131862-f183e539-61e2-4fa0-b344-5085493f78d3.png)


 Is there a way to force the video player refresh? So, for example, when you start playing the video, do you apply a refresh (Eliminate 5s delay), and when the TAB is in focus again, do you refresh again?

**Comment by deepch** [comment]
It appears if you minimize the tab?

**Comment by petryx** [comment]
This appears in two moments

- Initialization of video
- Minimization the tab or when the tab lost the focus

**Comment by vdalex25** [comment]
i added commit https://github.com/deepch/RTSPtoWSMP4f/commit/444db33c8553d909b7eebbf060b89b39b6bf25dd  fixed pause on  minimization the tab or when the tab lost the focus

**Comment by petryx** [comment]
Congratulations, now is working like a charm.
