### ISSUE TITLE
Is there any way to support IOS devices

### ISSUE THREAD

**Issue by sazima** [deepch/RTSPtoWSMP4f#7]
It works well on my PC chrome, but not work on IOS safari. I printed the error log on IOS safar,  which says
```
ReferenceError: Can't find variable: MediaSource
/static/js/app.js?ver=2020-10-14%2009%3a23%3a56.286920163%20%2b0800%20CST%20m%3d%2b13.941190558:11:25 global code@http://192.168.32.229:8083/static/js/app.js?ver=2020-10-14%2009%3a23%3a56.286920163%20%2b0800%20CST%20m%3d%2b13.941190558:11:25
```

**Comment by yeshivsher** [comment]
hi
did you solve it?

**Comment by deepch** [comment]
iOS device only safari iPad and Imac support'ed 
of you need iOS live try HLS if you need very low latency need WebRTC 
best practice iOS and android make app

**Comment by sazima** [comment]
> hi
> did you solve it?

No, I had to start a separate service for IOS with ffmeg

**Comment by deepch** [comment]
look this sample 

https://github.com/deepch/RTSPtoWeb

you can combine pc - ws iOS - webRTC Android - HLS and etc...

**Comment by yeshivsher** [comment]
Yes,but webrtc requires turn server... that's why I prefer using hls
BTW, which one is faster?
MSE or hls?

**Comment by deepch** [comment]
what does faster mean?

his - need buffer  and works better in poor connection conditions but there will be a delay from the real time.
webRTC - not delay 
MSE - not delay

lack of latency is not always good hls is more stable in terms of bad connections.

nvr or record = hls
live and phone call - webrtc
live browser - mse
