### ISSUE TITLE
hello,why? is bug?

### ISSUE THREAD

**Issue by lijieaa** [deepch/RTSPtoWSMP4f#8]
runtime error: index out of range [1] with length 1
I:/go1.13.15.windows-amd64/go/src/runtime/panic.go:75 (0x433ed9)
        goPanicIndex: panic(boundsError{x: int64(x), signed: true, y: y, code: boundsIndex})
D:/go-gateway/gopath/pkg/mod/github.com/deepch/vdk@v0.0.0-20200904010955-fccce247d096/format/mp4f/muxer.go:256 (0x887772)
        (*Muxer).WritePacket: stream := element.streams[pkt.Idx]
D:/go-gateway/RTSPtoWSMP4f/http.go:82 (0xb43422)
        ws: ready, buf, _ := muxer.WritePacket(pck, false)
D:/go-gateway/gopath/pkg/mod/golang.org/x/net@v0.0.0-20201010224723-4f7140c49acb/websocket/server.go:89 (0xb2b524)
        Server.serveWebSocket: s.Handler(conn)
D:/go-gateway/gopath/pkg/mod/golang.org/x/net@v0.0.0-20201010224723-4f7140c49acb/websocket/server.go:112 (0xb2b876)
        Handler.ServeHTTP: s.serveWebSocket(w, req)
D:/go-gateway/RTSPtoWSMP4f/http.go:39 (0xb44511)
        serveHTTP.func3: handler.ServeHTTP(c.Writer, c.Request)
D:/go-gateway/gopath/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xb076b2)
        (*Context).Next: c.handlers[c.index](c)
D:/go-gateway/gopath/pkg/mod/github.com/gin-gonic/gin@v1.6.3/recovery.go:83 (0xb23f4a)
        RecoveryWithWriter.func1: c.Next()
D:/go-gateway/gopath/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xb076b2)
        (*Context).Next: c.handlers[c.index](c)
D:/go-gateway/gopath/pkg/mod/github.com/gin-gonic/gin@v1.6.3/logger.go:241 (0xb2296b)
        LoggerWithConfig.func1: c.Next()
D:/go-gateway/gopath/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xb076b2)
        (*Context).Next: c.handlers[c.index](c)
D:/go-gateway/gopath/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409 (0xb149a1)
        (*Engine).handleHTTPRequest: c.Next()
D:/go-gateway/gopath/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367 (0xb1444c)
        (*Engine).ServeHTTP: engine.handleHTTPRequest(c)
I:/go1.13.15.windows-amd64/go/src/net/http/server.go:2831 (0x7f25f5)
        serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
I:/go1.13.15.windows-amd64/go/src/net/http/server.go:1919 (0x7ecac0)
        (*conn).serve: serverHandler{c.server}.ServeHTTP(w, w.req)
I:/go1.13.15.windows-amd64/go/src/runtime/asm_amd64.s:1357 (0x462fb0)
        goexit: BYTE    $0x90   // NOP

**Comment by deepch** [comment]
fix next version, try disable audio
