### ISSUE TITLE
Video does not start

### ISSUE THREAD

**Issue by xultz** [deepch/RTSPtoWSMP4f#9]
Hi, I'm trying to run the code to show an IP camera in my local network. I changed the config.json file to point to the IP camera (in my case, the line in the config.json is : "url": "rtsp://192.168.100.119:80/1", if I input this address to VLC it plays the video from the camera with no problems)
In the browser, it keeps the video spinning but does not show anything. The code is running in a Ubuntu server machine, and the browser in a Windows 10 machine (I tried in Firefox and Chrome).
The code outputs the following messages:
https://pastebin.com/36GvErs1

Are there any other logs that I can take a look to try to understand why the video is not working? Are there anything I can do to try to solve the issue and make it work?

Thank you!

**Comment by deepch** [comment]
try https://github.com/deepch/RTSPtoWeb
